
source: "/"
destination: "/"
lsi: false
pygments: true

sitename:  DCore
tagline: PHP Framework

production_url : http://dcore.bbfmedia.com/
url: http://dcore.bbfmedia.com/

safe:        true
auto:        true
baseurl:    http://dcore.bbfmedia.com/


pygments:    true
markdown:    rdiscount
permalink:   /blog/:year/:month/:day/:title/





navigation:
- text: Home
  url: /
  layout: default  
- text: About us
  url: /about/
  layout: page  
- text: Blog
  url: /blog/
  layout: archive


